kind: Service
apiVersion: v1
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  selector:
    app: catalog
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: http
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: ordering
  labels:
    app: ordering
spec:
  selector:
    app: ordering
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: ClusterIP
---